apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-configuration-nfspvc
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  RECLAIM_POLICY: {{ .Values.configurationNfspvc.reclaimPolicy | quote }}
  STORAGE_CLASS: {{ .Values.configurationNfspvc.storageClass | quote }}