apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-serving-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-nfspvc-dana-io-v1alpha1-nfspvc
  failurePolicy: Fail
  name: vnfspvc.kb.io
  rules:
  - apiGroups:
    - nfspvc.dana.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nfspvcs
  sideEffects: None