# permissions for end users to view nfspvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nfspvc-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nfs-operator
    app.kubernetes.io/part-of: nfs-operator
    app.kubernetes.io/managed-by: kustomize
  name: nfspvc-viewer-role
rules:
- apiGroups:
  - dana.io.dana.io
  resources:
  - nfspvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dana.io.dana.io
  resources:
  - nfspvcs/status
  verbs:
  - get
