# permissions for end users to edit nfspvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nfspvc-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nfspvc-operator
    app.kubernetes.io/part-of: nfspvc-operator
    app.kubernetes.io/managed-by: kustomize
  name: nfspvc-editor-role
rules:
- apiGroups:
  - nfspvc.dana.io
  resources:
  - nfspvcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nfspvc.dana.io
  resources:
  - nfspvcs/status
  verbs:
  - get
