name: pre-merge
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  e2e-tests:
    name: e2e-tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      IMAGE_REGISTRY: kind-registry:5000
      KIND_VERSION: v0.18.0
      K8S_VERSION: v1.26.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=2m
      - name: Configure insecure registry
        run: |
          #sudo cat /etc/docker/daemon.json
          
          # allow insecure registry but keep original config!
          sudo bash -c "cat <<EOF >/etc/docker/daemon.json
          {
            \"exec-opts\": [\"native.cgroupdriver=cgroupfs\"],
            \"cgroup-parent\": \"/actions_job\",
            \"insecure-registries\" : [\"${IMAGE_REGISTRY}\"]
          }
          EOF"
          
          #sudo cat /etc/docker/daemon.json
          sudo systemctl restart docker
          
          # same for podman
          sudo bash -c "cat <<EOF >/etc/containers/registries.conf
          [[registry]]
          location=\"${IMAGE_REGISTRY}\"
          insecure=true
          EOF"
          #sudo cat /etc/containers/registries.conf
      - name: Start kind cluster
        uses: container-tools/kind-action@v2
        with:
          version: ${{env.KIND_VERSION}}
          config: ./hack/kind-config.yaml
          node_image: kindest/node:${{env.K8S_VERSION}}
          kubectl_version: ${{env.K8S_VERSION}}
          registry: true
      - name: Deploy cert-manager
        run: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.yaml
      - name: Build image
        run: make docker-build docker-push IMG=${IMAGE_REGISTRY}/nfspvc-operator:test-${GITHUB_REF##*/}
      - name: Deploy to cluster
        run: make install deploy IMG=${IMAGE_REGISTRY}/nfspvc-operator:test-${GITHUB_REF##*/}
      - name: Run e2e tests
        run: make test-e2e